### ISSUE TITLE
Porting to other devices and architectures

### ISSUE THREAD

**Issue by Titaniumtown** [perilouswithadollarsign/cstrike15_src#9]
Since people have access to the source code, can it be ported to other devices like a raspberry pi? (lol)

**Comment by Titaniumtown** [comment]
It's kinda silly though

**Comment by bxff** [comment]
They probably did on there device, should probably remove this issue

**Comment by Titaniumtown** [comment]
*their

**Comment by perilouswithadollarsign** [comment]
@Titaniumtown again, i only published this so people could learn from it. as far as helping people goes, really i'm just gonna tell them to do whatever they want with it, because i haven't really done a deep dive into the code itself. pretty much any code in the world can be converted between devices and even languages, but its gonna take a lot of work. have at it if you want but it wont be easy.
